WIDTH = 100
HEIGHT = 100

# BEEHIVE CONSTANTS
REPRODUCTION_RATE = 0.1
NUM_BEES = 30   # Total number of bees to be added
CONSUME_RATE = 1
NECESSORY_FOOD = 10
NECTAR_NEEDED = 10

# RESOURCE CONSTANTS
NECTAR_QUANTITY = 10
NECTAR_SD = 2
CARRY_CAPACITY = 1

# MODEL CONSTANTS
RESOURCE_DENSITY = 0.1
NR_HIVES = 1

# BEE CONSTANTS
BABY_FEED = 0.5  # TODO : Add heterogeneity  
BABY_AGELIMIT = 10  # TODO : Add heterogeneity